# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  - name: hello-world
    schedule: "*/1 * * * *"
    image:
      repository: hello-world
      tag: latest
      imagePullPolicy: Always
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
  - name: hello-world-2
    schedule: "*/2 * * * *"
    image:
      repository: hello-world
      tag: latest
      imagePullPolicy: Always
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
