apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}-job
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ .Values.name }}-pod
          labels:
            app: {{ .Values.name }}

        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              {{- with .Values.env }}
              env:
                {{- toYaml . | nindent 12 }}
              {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
