name: hello-world
schedule: "*/1 * * * *"
image:
  repository: hello-world
  tag: latest
  imagePullPolicy: Always
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
concurrencyPolicy: Allow
restartPolicy: OnFailure
